/*
 * generated by Xtext 2.25.0
 */
package lphy.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LPhyUiModule extends AbstractLPhyUiModule {

	public LPhyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
