/**
 * generated by Xtext 2.25.0
 */
package lphy.dsl.lPhy;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Distribution Type Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lphy.dsl.lPhy.LPhyPackage#getDistributionTypeSpecification()
 * @model
 * @generated
 */
public interface DistributionTypeSpecification extends EObject
{
} // DistributionTypeSpecification
