/**
 * generated by Xtext 2.25.0
 */
package lphy.dsl.lPhy;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Law Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lphy.dsl.lPhy.LPhyPackage#getLawNode()
 * @model
 * @generated
 */
public interface LawNode extends EObject
{
} // LawNode
