/**
 * generated by Xtext 2.25.0
 */
package lphy.dsl.lPhy;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dist</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lphy.dsl.lPhy.LPhyDist#getDistributionType <em>Distribution Type</em>}</li>
 * </ul>
 *
 * @see lphy.dsl.lPhy.LPhyPackage#getLPhyDist()
 * @model
 * @generated
 */
public interface LPhyDist extends DistributionTypeSpecification
{
  /**
   * Returns the value of the '<em><b>Distribution Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distribution Type</em>' reference.
   * @see #setDistributionType(LPhyModel)
   * @see lphy.dsl.lPhy.LPhyPackage#getLPhyDist_DistributionType()
   * @model
   * @generated
   */
  LPhyModel getDistributionType();

  /**
   * Sets the value of the '{@link lphy.dsl.lPhy.LPhyDist#getDistributionType <em>Distribution Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distribution Type</em>' reference.
   * @see #getDistributionType()
   * @generated
   */
  void setDistributionType(LPhyModel value);

} // LPhyDist
