/**
 * generated by Xtext 2.25.0
 */
package lphy.dsl.lPhy.impl;

import lphy.dsl.lPhy.DistributionTypeSpecification;
import lphy.dsl.lPhy.LPhyPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Distribution Type Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DistributionTypeSpecificationImpl extends MinimalEObjectImpl.Container implements DistributionTypeSpecification
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DistributionTypeSpecificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LPhyPackage.Literals.DISTRIBUTION_TYPE_SPECIFICATION;
  }

} //DistributionTypeSpecificationImpl
