/*
 * generated by Xtext 2.25.0
 */
package lphy.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LinguaPhyloStandaloneSetup extends LinguaPhyloStandaloneSetupGenerated {

	public static void doSetup() {
		new LinguaPhyloStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
