/*
 * generated by Xtext 2.25.0
 */
package lphy.dsl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractLPhyScopeProvider extends XbaseBatchScopeProvider {
}
